// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVAkJHndRbcXQMFLEqd4tX_jcxSSrPe-Y',
    appId: '1:514603610933:web:20e1f1b81a32a9c881927c',
    messagingSenderId: '514603610933',
    projectId: 'nordus-app',
    authDomain: 'nordus-app.firebaseapp.com',
    databaseURL: 'https://nordus-app-default-rtdb.firebaseio.com',
    storageBucket: 'nordus-app.appspot.com',
    measurementId: 'G-SX4TRLTRKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQiVWpiv7Fz72Q3fZPVYbyiSPFHkrev_Q',
    appId: '1:514603610933:android:2d77df3057b949db81927c',
    messagingSenderId: '514603610933',
    projectId: 'nordus-app',
    databaseURL: 'https://nordus-app-default-rtdb.firebaseio.com',
    storageBucket: 'nordus-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvlPjmFhc5mi1FlAz2ETnpZe74sqvqQBo',
    appId: '1:514603610933:ios:66c29f5f3adf8ee281927c',
    messagingSenderId: '514603610933',
    projectId: 'nordus-app',
    databaseURL: 'https://nordus-app-default-rtdb.firebaseio.com',
    storageBucket: 'nordus-app.appspot.com',
    iosBundleId: 'com.example.lddmPucBarberapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvlPjmFhc5mi1FlAz2ETnpZe74sqvqQBo',
    appId: '1:514603610933:ios:66c29f5f3adf8ee281927c',
    messagingSenderId: '514603610933',
    projectId: 'nordus-app',
    databaseURL: 'https://nordus-app-default-rtdb.firebaseio.com',
    storageBucket: 'nordus-app.appspot.com',
    iosBundleId: 'com.example.lddmPucBarberapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVAkJHndRbcXQMFLEqd4tX_jcxSSrPe-Y',
    appId: '1:514603610933:web:d48b4df0df1ac2a581927c',
    messagingSenderId: '514603610933',
    projectId: 'nordus-app',
    authDomain: 'nordus-app.firebaseapp.com',
    databaseURL: 'https://nordus-app-default-rtdb.firebaseio.com',
    storageBucket: 'nordus-app.appspot.com',
    measurementId: 'G-0FRPXZ249R',
  );
}
